import type { SimData } from "../game/types";

export const pilotData: SimData = {
  nodes: [
    // Resources
    {
      id: "authority",
      type: "resource",
      name: "Authority",
      description: "Authority capital used to change stances.",
      domain: { min: 0, max: 50, clamp: true },
      category: "Resource",
    },
    {
      id: "budget",
      type: "resource",
      name: "Budget",
      description: "Liquid funds available for programs and expansion.",
      domain: { min: 0, max: 100, clamp: true },
      category: "Resource",
    },

    // Governance stances
    {
      id: "authorityCentralization",
      type: "stance",
      name: "Authority Centralization",
      description: "How centralized governance is.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "disciplinaryStrictness",
      type: "stance",
      name: "Disciplinary Strictness",
      description: "How strictly rules are enforced.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "clergyAccountability",
      type: "stance",
      name: "Clergy Accountability",
      description: "How strongly clergy are reviewed and supervised.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "boundaryEnforcement",
      type: "stance",
      name: "Boundary Enforcement",
      description: "How explicit and strict boundaries are.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "reformOpenness",
      type: "stance",
      name: "Reform Openness",
      description: "How open leadership is to change and reform.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },

    // Governance indicators
    {
      id: "institutionalLegitimacy",
      type: "indicator",
      name: "Institutional Legitimacy",
      description: "Perceived right to lead and decide.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },
    {
      id: "factionalism",
      type: "indicator",
      name: "Factionalism",
      description: "Internal political division among elites and regions.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },
    {
      id: "schismPressure",
      type: "indicator",
      name: "Schism Pressure",
      description: "Risk of fragmentation into separate bodies.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },

    // Doctrine stances
    {
      id: "scriptureAuthority",
      type: "stance",
      name: "Authority of Scripture",
      description: "How final and binding Scripture is treated.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Doctrine",
      stanceCost: { base: 1, perPoint: 7, maxDelta: 0.25 },
    },
    {
      id: "traditionAuthority",
      type: "stance",
      name: "Role of Tradition",
      description: "How binding tradition is in teaching and governance.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Doctrine",
      stanceCost: { base: 1, perPoint: 7, maxDelta: 0.25 },
    },
    {
      id: "salvationEmphasis",
      type: "stance",
      name: "Salvation Emphasis",
      description: "Emphasis on sanctification process versus declarative justification.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Doctrine",
      stanceCost: { base: 1, perPoint: 7, maxDelta: 0.25 },
    },
    {
      id: "sacramentalTheology",
      type: "stance",
      name: "Sacramental Theology",
      description: "Symbolic to means of grace orientation.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Doctrine",
      stanceCost: { base: 1, perPoint: 7, maxDelta: 0.25 },
    },
    {
      id: "charismaticGifts",
      type: "stance",
      name: "Charismatic Gifts",
      description: "Cessationist to active gifts orientation.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Doctrine",
      stanceCost: { base: 1, perPoint: 7, maxDelta: 0.25 },
    },

    // Doctrine indicators
    {
      id: "doctrinalIdentityClarity",
      type: "indicator",
      name: "Doctrinal Identity Clarity",
      description: "How clearly the church knows what it teaches.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Doctrine",
    },
    {
      id: "theologicalTension",
      type: "indicator",
      name: "Theological Tension",
      description: "Internal strain caused by doctrinal mismatch and debates.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Doctrine",
    },
    {
      id: "reformMomentum",
      type: "indicator",
      name: "Reform Momentum",
      description: "Pressure to reinterpret and restructure beliefs and practices.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Doctrine",
    },

    // Worship and Practice stances
    {
      id: "sacramentalCentrality",
      type: "stance",
      name: "Sacramental Centrality",
      description: "How central sacraments are in religious life.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "baptismalInclusion",
      type: "stance",
      name: "Baptismal Inclusion",
      description: "Restrictive to inclusive baptismal practice.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "eucharisticFrequency",
      type: "stance",
      name: "Eucharistic Frequency",
      description: "How often the Lords Supper is practiced.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "liturgicalFormality",
      type: "stance",
      name: "Liturgical Formality",
      description: "Spontaneous to highly structured liturgy.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "participationExpectation",
      type: "stance",
      name: "Participation Expectation",
      description: "How strongly attendance and participation are expected.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "teachingIntensity",
      type: "stance",
      name: "Teaching Intensity",
      description: "How intensive instruction and formation are in worship life.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },

    // Worship and Practice indicators
    {
      id: "sacramentalParticipationRate",
      type: "indicator",
      name: "Sacramental Participation Rate",
      description: "How many members regularly receive sacraments.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
    },
    {
      id: "worshipEngagement",
      type: "indicator",
      name: "Worship Engagement",
      description: "Depth of participation and involvement in worship life.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
    },
    {
      id: "practiceDriftRate",
      type: "indicator",
      name: "Practice Drift Rate",
      description: "How fast worship practices diverge over time.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
    },
    {
      id: "clergyRitualLoad",
      type: "indicator",
      name: "Clergy Ritual Load",
      description: "Strain on clergy from ritual and service obligations.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Worship",
    },

    // Finance and Assets stances
    {
      id: "fundingModel",
      type: "stance",
      name: "Funding Model",
      description: "Voluntary giving to strongly expected contributions.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "financialCentralization",
      type: "stance",
      name: "Financial Centralization",
      description: "Local control to central treasury.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "clergyCompensation",
      type: "stance",
      name: "Clergy Compensation",
      description: "Ascetic to professionalized support.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "financialTransparency",
      type: "stance",
      name: "Financial Transparency",
      description: "Opaque to fully transparent finances.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },

    // Finance and Assets indicators
    {
      id: "revenueStability",
      type: "indicator",
      name: "Revenue Stability",
      description: "How stable income is over time.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance",
    },
    {
      id: "financialLegitimacy",
      type: "indicator",
      name: "Financial Legitimacy",
      description: "Perceived moral legitimacy of wealth and spending.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance",
    },
    {
      id: "corruptionPressure",
      type: "indicator",
      name: "Corruption Pressure",
      description: "Systemic risk of misuse of resources.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance",
    },

    // Care and Charity stances (programs as stances)
    {
      id: "foodPantryProgram",
      type: "stance",
      name: "Food Pantry",
      description: "Operate a pantry for basic food assistance.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
      stanceCost: { base: 0.5, perPoint: 3, maxDelta: 0.5 },
    },
    {
      id: "clinicProgram",
      type: "stance",
      name: "Clinics and Medical Aid",
      description: "Provide medical care services for the community.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
      stanceCost: { base: 0.5, perPoint: 4, maxDelta: 0.5 },
    },
    {
      id: "disasterReliefProgram",
      type: "stance",
      name: "Disaster Relief",
      description: "Maintain a rapid response disaster relief capacity.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
      stanceCost: { base: 0.5, perPoint: 4, maxDelta: 0.5 },
    },
    {
      id: "widowsSupportProgram",
      type: "stance",
      name: "Widows and Clergy Support",
      description: "Provide support for widows and clergy families.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
      stanceCost: { base: 0.5, perPoint: 3, maxDelta: 0.5 },
    },
    {
      id: "homelessShelterProgram",
      type: "stance",
      name: "Homeless Shelter",
      description: "Operate a shelter and stabilization services.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
      stanceCost: { base: 0.5, perPoint: 4, maxDelta: 0.5 },
    },

    // Care and Charity indicators
    {
      id: "compassionCredibility",
      type: "indicator",
      name: "Compassion Credibility",
      description: "Perceived sincerity and effectiveness of care.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
    },
    {
      id: "dependencyRate",
      type: "indicator",
      name: "Dependency Rate",
      description: "How much people become reliant on aid over time.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
    },
    {
      id: "volunteerCapacity",
      type: "indicator",
      name: "Volunteer Capacity",
      description: "Availability of unpaid labor for programs.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
    },
    {
      id: "burnoutPressure",
      type: "indicator",
      name: "Burnout Pressure",
      description: "Exhaustion caused by sustained care work.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Care",
    },

    // Mission and Expansion stances
    {
      id: "missionPriority",
      type: "stance",
      name: "Mission Priority",
      description: "Defensive preservation to aggressive expansion focus.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "culturalAdaptation",
      type: "stance",
      name: "Cultural Adaptation",
      description: "Rigid identity to adaptive contextualization.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "evangelismMethod",
      type: "stance",
      name: "Evangelism Method",
      description: "Relational outreach to mass outreach orientation.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "conversionThreshold",
      type: "stance",
      name: "Conversion Threshold",
      description: "Low barrier to high commitment membership threshold.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },
    {
      id: "missionaryAutonomy",
      type: "stance",
      name: "Missionary Autonomy",
      description: "Tightly controlled to highly autonomous mission work.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
      stanceCost: { base: 1, perPoint: 5, maxDelta: 0.35 },
    },

    // Mission and Expansion indicators
    {
      id: "conversionRate",
      type: "indicator",
      name: "Conversion Rate",
      description: "Speed of new member acquisition.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
    },
    {
      id: "retentionQuality",
      type: "indicator",
      name: "Retention Quality",
      description: "How many converts remain long term.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
    },
    {
      id: "culturalResistance",
      type: "indicator",
      name: "Cultural Resistance",
      description: "Opposition encountered from local societies and rivals.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
    },
    {
      id: "identityDilution",
      type: "indicator",
      name: "Identity Dilution",
      description: "Loss of doctrinal and ritual clarity through growth.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission",
    },
  ],

  effects: [
    // Baselines
    { sourceId: "_default_", targetId: "budget", magnitude: 0.25 },
    { sourceId: "_default_", targetId: "authority", magnitude: 0.15 },

    // Governance to governance indicators
    { sourceId: "authorityCentralization", targetId: "factionalism", magnitude: 0.02 },
    { sourceId: "disciplinaryStrictness", targetId: "institutionalLegitimacy", magnitude: 0.015 },
    { sourceId: "disciplinaryStrictness", targetId: "schismPressure", magnitude: 0.02 },
    { sourceId: "clergyAccountability", targetId: "institutionalLegitimacy", magnitude: 0.02 },
    { sourceId: "clergyAccountability", targetId: "corruptionPressure", magnitude: -0.02 },
    { sourceId: "boundaryEnforcement", targetId: "schismPressure", magnitude: 0.02 },
    { sourceId: "reformOpenness", targetId: "reformMomentum", magnitude: 0.03 },
    { sourceId: "reformOpenness", targetId: "factionalism", magnitude: 0.01 },

    // Doctrine stances to doctrine indicators
    { sourceId: "scriptureAuthority", targetId: "doctrinalIdentityClarity", magnitude: 0.02, inertiaTurns: 1 },
    { sourceId: "traditionAuthority", targetId: "doctrinalIdentityClarity", magnitude: 0.02, inertiaTurns: 1 },
    { sourceId: "traditionAuthority", targetId: "reformMomentum", magnitude: -0.02, inertiaTurns: 2 },
    { sourceId: "salvationEmphasis", targetId: "theologicalTension", magnitude: 0.015, inertiaTurns: 2 },
    { sourceId: "sacramentalTheology", targetId: "theologicalTension", magnitude: 0.015, inertiaTurns: 2 },
    { sourceId: "charismaticGifts", targetId: "theologicalTension", magnitude: 0.02, inertiaTurns: 1 },

    // Worship stances to worship indicators
    { sourceId: "sacramentalCentrality", targetId: "sacramentalParticipationRate", magnitude: 0.03, inertiaTurns: 1 },
    { sourceId: "baptismalInclusion", targetId: "conversionRate", magnitude: 0.02, inertiaTurns: 2 },
    { sourceId: "eucharisticFrequency", targetId: "clergyRitualLoad", magnitude: 0.02 },
    { sourceId: "liturgicalFormality", targetId: "practiceDriftRate", magnitude: -0.02, inertiaTurns: 2 },
    { sourceId: "participationExpectation", targetId: "worshipEngagement", magnitude: 0.02, inertiaTurns: 1 },
    { sourceId: "participationExpectation", targetId: "budget", magnitude: 0.12, inertiaTurns: 1 },
    { sourceId: "teachingIntensity", targetId: "retentionQuality", magnitude: 0.02, inertiaTurns: 3 },
    { sourceId: "teachingIntensity", targetId: "doctrinalIdentityClarity", magnitude: 0.015, inertiaTurns: 3 },

    // Finance stances to finance indicators and resources
    { sourceId: "fundingModel", targetId: "budget", magnitude: 0.18, inertiaTurns: 1 },
    { sourceId: "fundingModel", targetId: "revenueStability", magnitude: 0.02, inertiaTurns: 2 },
    { sourceId: "financialCentralization", targetId: "revenueStability", magnitude: 0.015, inertiaTurns: 2 },
    { sourceId: "financialCentralization", targetId: "corruptionPressure", magnitude: 0.015, inertiaTurns: 2 },
    { sourceId: "clergyCompensation", targetId: "institutionalLegitimacy", magnitude: -0.01, inertiaTurns: 2 },
    { sourceId: "clergyCompensation", targetId: "retentionQuality", magnitude: 0.01, inertiaTurns: 3 },
    { sourceId: "financialTransparency", targetId: "financialLegitimacy", magnitude: 0.03, inertiaTurns: 1 },
    { sourceId: "financialTransparency", targetId: "corruptionPressure", magnitude: -0.03, inertiaTurns: 1 },

    // Care programs to care indicators and budget
    { sourceId: "foodPantryProgram", targetId: "compassionCredibility", magnitude: 0.02, inertiaTurns: 1 },
    { sourceId: "foodPantryProgram", targetId: "dependencyRate", magnitude: 0.02, inertiaTurns: 3 },
    { sourceId: "foodPantryProgram", targetId: "budget", magnitude: -0.12 },
    { sourceId: "clinicProgram", targetId: "compassionCredibility", magnitude: 0.03, inertiaTurns: 2 },
    { sourceId: "clinicProgram", targetId: "burnoutPressure", magnitude: 0.015, inertiaTurns: 2 },
    { sourceId: "clinicProgram", targetId: "budget", magnitude: -0.18 },
    { sourceId: "disasterReliefProgram", targetId: "compassionCredibility", magnitude: 0.03, inertiaTurns: 1 },
    { sourceId: "disasterReliefProgram", targetId: "burnoutPressure", magnitude: 0.02, inertiaTurns: 1 },
    { sourceId: "disasterReliefProgram", targetId: "budget", magnitude: -0.15 },
    { sourceId: "widowsSupportProgram", targetId: "retentionQuality", magnitude: 0.015, inertiaTurns: 2 },
    { sourceId: "widowsSupportProgram", targetId: "budget", magnitude: -0.1 },
    { sourceId: "homelessShelterProgram", targetId: "compassionCredibility", magnitude: 0.03, inertiaTurns: 2 },
    { sourceId: "homelessShelterProgram", targetId: "dependencyRate", magnitude: 0.03, inertiaTurns: 3 },
    { sourceId: "homelessShelterProgram", targetId: "burnoutPressure", magnitude: 0.03, inertiaTurns: 2 },
    { sourceId: "homelessShelterProgram", targetId: "budget", magnitude: -0.22 },

    // Care and worship to volunteer capacity
    { sourceId: "worshipEngagement", targetId: "volunteerCapacity", magnitude: 0.02, inertiaTurns: 2 },
    { sourceId: "burnoutPressure", targetId: "volunteerCapacity", magnitude: -0.03, inertiaTurns: 1 },

    // Mission stances to mission indicators and budget
    { sourceId: "missionPriority", targetId: "conversionRate", magnitude: 0.03, inertiaTurns: 2 },
    { sourceId: "missionPriority", targetId: "budget", magnitude: -0.18, inertiaTurns: 1 },
    { sourceId: "culturalAdaptation", targetId: "conversionRate", magnitude: 0.02, inertiaTurns: 2 },
    { sourceId: "culturalAdaptation", targetId: "identityDilution", magnitude: 0.02, inertiaTurns: 2 },
    { sourceId: "evangelismMethod", targetId: "conversionRate", magnitude: 0.02, inertiaTurns: 1 },
    { sourceId: "evangelismMethod", targetId: "culturalResistance", magnitude: 0.015, inertiaTurns: 2 },
    { sourceId: "conversionThreshold", targetId: "retentionQuality", magnitude: 0.02, inertiaTurns: 3 },
    { sourceId: "conversionThreshold", targetId: "conversionRate", magnitude: -0.015, inertiaTurns: 2 },
    { sourceId: "missionaryAutonomy", targetId: "identityDilution", magnitude: 0.02, inertiaTurns: 3 },
    { sourceId: "missionaryAutonomy", targetId: "schismPressure", magnitude: 0.015, inertiaTurns: 3 },

    // System couplings
    { sourceId: "doctrinalIdentityClarity", targetId: "institutionalLegitimacy", magnitude: 0.02, inertiaTurns: 2 },
    { sourceId: "doctrinalIdentityClarity", targetId: "identityDilution", magnitude: -0.02, inertiaTurns: 2 },
    { sourceId: "theologicalTension", targetId: "factionalism", magnitude: 0.02, inertiaTurns: 2 },
    { sourceId: "factionalism", targetId: "schismPressure", magnitude: 0.03, inertiaTurns: 2 },
    { sourceId: "compassionCredibility", targetId: "institutionalLegitimacy", magnitude: 0.02, inertiaTurns: 2 },
    { sourceId: "corruptionPressure", targetId: "institutionalLegitimacy", magnitude: -0.03, inertiaTurns: 2 },
    { sourceId: "financialLegitimacy", targetId: "institutionalLegitimacy", magnitude: 0.02, inertiaTurns: 2 },

    // Resources feedback
    { sourceId: "institutionalLegitimacy", targetId: "authority", magnitude: 0.25, inertiaTurns: 1 },
    { sourceId: "schismPressure", targetId: "authority", magnitude: -0.35, inertiaTurns: 1 },
    { sourceId: "corruptionPressure", targetId: "authority", magnitude: -0.25, inertiaTurns: 1 },
    { sourceId: "budget", targetId: "authority", magnitude: 0.02, inertiaTurns: 1 },
  ],
};
