import type { SimData } from "../game/types";

export const pilotData: SimData = {
  nodes: [
    {
      id: "confessionalStrictness",
      type: "stance",
      name: "Confessional Strictness",
      description: "Policy stance slider.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Doctrine",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "seminaryInvestment",
      type: "stance",
      name: "Seminary Investment",
      description: "Investment in training and education.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Policy",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "ecumenismOpenness",
      type: "stance",
      name: "Ecumenism Openness",
      description: "Willingness to cooperate across lines.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Doctrine",
      stanceCost: { base: 1, perPoint: 6, maxDelta: 0.3 },
    },
    {
      id: "clergyQuality",
      type: "indicator",
      name: "Clergy Quality",
      description: "Training and competence.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Policy",
    },
    {
      id: "doctrinalClarity",
      type: "indicator",
      name: "Doctrinal Clarity",
      description: "How coherent teaching and confession are.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Doctrine",
    },
    {
      id: "unityCohesion",
      type: "indicator",
      name: "Unity Cohesion",
      description: "Internal cohesion across factions.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Church",
    },
    {
      id: "disciplineEnforcement",
      type: "stance",
      name: "Discipline Enforcement",
      description: "How strongly discipline is applied.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Church",
    },
    {
      id: "schismPressure",
      type: "indicator",
      name: "Schism Pressure",
      description: "Risk of fragmentation.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Church",
    },
    {
      id: "publicLegitimacy",
      type: "indicator",
      name: "Public Legitimacy",
      description: "Standing with wider society.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Church",
    },
    {
      id: "institutionalIntegrity",
      type: "indicator",
      name: "Institutional Integrity",
      description: "Trust and lack of corruption.",
      domain: { min: 0, max: 1, clamp: false },
      category: "Church",
    },
    {
      id: "authority",
      type: "resource",
      name: "Authority",
      description: "Authority capital as a resource node.",
      domain: { min: 0, max: 20, clamp: false },
      category: "Resource",
    },
  ],
  effects: [
    { sourceId: "_default_", targetId: "education", magnitude: 0.04 },
    {
      sourceId: "confessionalStrictness",
      targetId: "doctrinalClarity",
      magnitude: 0.03,
      inertiaTurns: 1,
    },
    {
      sourceId: "confessionalStrictness",
      targetId: "schismPressure",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "seminaryInvestment",
      targetId: "clergyQuality",
      magnitude: 0.03,
      inertiaTurns: 4,
    },
    {
      sourceId: "disciplineEnforcement",
      targetId: "institutionalIntegrity",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "disciplineEnforcement",
      targetId: "unityCohesion",
      magnitude: -0.03,
    },
    {
      sourceId: "ecumenismOpenness",
      targetId: "publicLegitimacy",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "clergyQuality",
      targetId: "doctrinalClarity",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "doctrinalClarity",
      targetId: "unityCohesion",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "doctrinalClarity",
      targetId: "schismPressure",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "institutionalIntegrity",
      targetId: "publicLegitimacy",
      magnitude: 0.02,
      inertiaTurns: 2,
    },

    // Simple authority drift
    {
      sourceId: "_default_",
      targetId: "authority",
      magnitude: 0.5,
    },
    {
      sourceId: "schismPressure",
      targetId: "authority",
      magnitude: -0.5,
    },
    {
      sourceId: "institutionalIntegrity",
      targetId: "authority",
      magnitude: 0.5,
    },
  ],
};
