// src/content/pilotData.ts
import type { SimData, ValueLabel, StanceSpec } from "../game/types";

const stanceCostStd = { base: 1, perPoint: 6, maxDelta: 0.3 };
const stanceCostSoft = { base: 1, perPoint: 5, maxDelta: 0.35 };

const resourceAuthorityLabels: ValueLabel[] = [
  { min: 0, max: 5, label: "Empty" },
  { min: 5, max: 15, label: "Low" },
  { min: 15, max: 30, label: "Stable" },
  { min: 30, max: 50, label: "Abundant" },
];

const resourceBudgetLabels: ValueLabel[] = [
  { min: 0, max: 15, label: "Tight" },
  { min: 15, max: 40, label: "Limited" },
  { min: 40, max: 70, label: "Healthy" },
  { min: 70, max: 100, label: "Flush" },
];

const continuous01: StanceSpec = { kind: "continuous", step: 0.01 };

const discreteLowMidHigh: StanceSpec = {
  kind: "discrete",
  levels: [
    { value: 0.0, label: "Low" },
    { value: 0.5, label: "Medium" },
    { value: 1.0, label: "High" },
  ],
};

export const pilotData: SimData = {
  nodes: [
    // Resources
    {
      id: "authority",
      type: "resource",
      name: "Authority",
      description: "Authority capital used to change stances.",
      domain: { min: 0, max: 50, clamp: true },
      category: "Resource",
      valueLabels: resourceAuthorityLabels,
    },
    {
      id: "budget",
      type: "resource",
      name: "Budget",
      description: "Budget available for operations, service, and mission.",
      domain: { min: 0, max: 100, clamp: true },
      category: "Resource",
      valueLabels: resourceBudgetLabels,
    },

    // Governance stances
    {
      id: "authorityCentralization",
      type: "stance",
      name: "Authority Centralization",
      description: "Local autonomy versus centralized hierarchy.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: stanceCostStd,
      stance: continuous01,
      // startActive: false,
    },
    {
      id: "decisionFormalization",
      type: "stance",
      name: "Decision Formalization",
      description: "Informal consensus versus formal procedures.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "leadershipAccountability",
      type: "stance",
      name: "Leadership Accountability",
      description: "Trust based oversight versus audit and review heavy.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "disciplinaryStrictness",
      type: "stance",
      name: "Disciplinary Strictness",
      description: "Pastoral leniency versus legalistic enforcement.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: stanceCostStd,
      stance: continuous01,
    },
    {
      id: "leadershipDevelopmentInvestment",
      type: "stance",
      name: "Leadership Development Investment",
      description: "Ad hoc training versus systematic training.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },

    // Governance indicators
    {
      id: "governanceEffectiveness",
      type: "indicator",
      name: "Governance Effectiveness",
      description: "How well decisions are implemented.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },
    {
      id: "congregationalCohesion",
      type: "indicator",
      name: "Congregational Cohesion",
      description: "Unity and alignment across congregations.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },
    {
      id: "memberLoyalty",
      type: "indicator",
      name: "Member Loyalty",
      description: "Retention and emotional attachment to the denomination.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },
    {
      id: "leadershipTrust",
      type: "indicator",
      name: "Leadership Trust",
      description: "Confidence in leaders ability.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },
    {
      id: "leadershipCapacity",
      type: "indicator",
      name: "Leadership Capacity",
      description: "Quality and number of active leaders.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },
    {
      id: "governanceReach",
      type: "indicator",
      name: "Governance Reach",
      description:
        "Number and scale of congregations under effective governance.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Governance",
    },

    // Belief and Teaching stances
    {
      id: "doctrinalBoundaryWidth",
      type: "stance",
      name: "Doctrinal Boundary Width",
      description: "Broad orthodoxy versus narrow confessionalism.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
      stanceCost: stanceCostStd,
      stance: continuous01,
    },
    {
      id: "teachingCentralization",
      type: "stance",
      name: "Teaching Centralization",
      description: "Local interpretation versus standardized curriculum.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "teachingAccessibilityPriority",
      type: "stance",
      name: "Teaching Accessibility Priority",
      description: "Academic depth versus plain instruction.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "theologicalDepthEmphasis",
      type: "stance",
      name: "Theological Depth Emphasis",
      description: "Simplified faith versus high intellectual theology.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "catechesisIntensity",
      type: "stance",
      name: "Catechesis Intensity",
      description: "Minimal instruction versus intensive formation.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },

    // Belief and Teaching indicators
    {
      id: "doctrinalClarity",
      type: "indicator",
      name: "Doctrinal Clarity",
      description: "Consistency of teaching across congregations.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
    },
    {
      id: "confessionalRigidity",
      type: "indicator",
      name: "Confessional Rigidity",
      description: "Resistance to doctrinal change.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
    },
    {
      id: "theologicalComplexity",
      type: "indicator",
      name: "Theological Complexity",
      description: "Sophistication of beliefs and difficulty to understand.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
    },
    {
      id: "layTheologicalLiteracy",
      type: "indicator",
      name: "Lay Theological Literacy",
      description: "Understanding of theology among regular members.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
    },
    {
      id: "clergyQuality",
      type: "indicator",
      name: "Clergy Quality",
      description: "Competence of clergy.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
    },
    {
      id: "faithAdherence",
      type: "indicator",
      name: "Faith Adherence",
      description: "Degree to which members internalize beliefs.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
    },
    {
      id: "teachingAccessibility",
      type: "indicator",
      name: "Teaching Accessibility",
      description: "How easy it is for members to understand the teaching.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Belief and Teaching",
    },

    // Rituals and Practice stances
    {
      id: "ritualIntensity",
      type: "stance",
      name: "Ritual Intensity",
      description: "Minimal obligations versus high ritual demands.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "ritualStandardization",
      type: "stance",
      name: "Ritual Standardization",
      description: "Local variation versus uniform practice.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "clergyExclusivityInRituals",
      type: "stance",
      name: "Clergy Exclusivity in Rituals",
      description: "Shared roles versus clergy exclusive.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
      stanceCost: stanceCostStd,
      stance: continuous01,
    },
    {
      id: "emotionalExpressionNorms",
      type: "stance",
      name: "Emotional Expression Norms",
      description: "Reserved versus expressive.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "participationExpectation",
      type: "stance",
      name: "Participation Expectation",
      description: "Voluntary versus obligatory participation.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },

    // Rituals and Practice indicators
    {
      id: "leadershipBurden",
      type: "indicator",
      name: "Leadership Burden",
      description: "Workload and stress on clergy for rituals and practice.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
    },
    {
      id: "memberBurden",
      type: "indicator",
      name: "Member Burden",
      description: "Effort required of members to participate.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
    },
    {
      id: "activeParticipation",
      type: "indicator",
      name: "Active Participation",
      description: "Share of members regularly participating in rituals.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
    },
    {
      id: "ritualCohesion",
      type: "indicator",
      name: "Ritual Cohesion",
      description: "Uniformity of practice across congregations.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
    },
    {
      id: "emotionalVolatility",
      type: "indicator",
      name: "Emotional Volatility",
      description: "Fluctuations in morale and ritual engagement.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
    },
    {
      id: "ritualQuality",
      type: "indicator",
      name: "Ritual Quality",
      description: "Fidelity and depth of worship and ritual performance.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
    },
    {
      id: "worshipEngagement",
      type: "indicator",
      name: "Worship Engagement",
      description: "Participation quality during services.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Rituals and Practice",
    },

    // Finance and Assets stances
    {
      id: "fundingModel",
      type: "stance",
      name: "Funding Model",
      description: "Voluntary giving versus expected contributions.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
      stanceCost: stanceCostSoft,
      stance: discreteLowMidHigh,
    },
    {
      id: "financialCentralization",
      type: "stance",
      name: "Financial Centralization",
      description: "Local budgets versus central treasury.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "transparencyLevel",
      type: "stance",
      name: "Transparency Level",
      description: "Opaque versus fully transparent reporting.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "spendingPriority",
      type: "stance",
      name: "Spending Priority",
      description: "Internal maintenance versus external mission and service.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "reservePolicy",
      type: "stance",
      name: "Reserve Policy",
      description: "Spend aggressively versus build reserves.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
      stanceCost: stanceCostSoft,
      stance: discreteLowMidHigh,
    },

    // Finance and Assets indicators
    {
      id: "debtAndReserves",
      type: "indicator",
      name: "Debt and Reserves",
      description: "Overall financial buffer.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "income",
      type: "indicator",
      name: "Income",
      description: "Total incoming funds.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "expenditure",
      type: "indicator",
      name: "Expenditure",
      description: "Total expenses.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "currentEconomy",
      type: "indicator",
      name: "Current Economy",
      description: "External economic context modifier.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "financialStability",
      type: "indicator",
      name: "Financial Stability",
      description: "Risk of insolvency or crisis.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "offering",
      type: "indicator",
      name: "Offering",
      description: "Contributions from members.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "donations",
      type: "indicator",
      name: "Donations",
      description: "Extra contributions or external funding.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "financialTransparencyIndex",
      type: "indicator",
      name: "Financial Transparency",
      description: "Clarity and openness in reporting.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "financialTrust",
      type: "indicator",
      name: "Financial Trust",
      description: "Member and public confidence in finances.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "corruptionRisk",
      type: "indicator",
      name: "Corruption Risk",
      description: "Likelihood of misuse of funds.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },
    {
      id: "financialBurden",
      type: "indicator",
      name: "Financial Burden",
      description: "Pressure on members and congregations.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Finance and Assets",
    },

    // Service and Charity stances
    {
      id: "serviceOrientation",
      type: "stance",
      name: "Service Orientation",
      description: "Internal care versus external service.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "serviceScaleStrategy",
      type: "stance",
      name: "Service Scale Strategy",
      description: "Many small programs versus few large institutions.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "serviceProfessionalization",
      type: "stance",
      name: "Professionalization Level",
      description: "Volunteer driven versus staff driven.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
      stanceCost: stanceCostSoft,
      stance: discreteLowMidHigh,
    },
    {
      id: "aidConditionality",
      type: "stance",
      name: "Conditionality of Aid",
      description: "Unconditional versus conditional assistance.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "serviceVisibility",
      type: "stance",
      name: "Visibility of Service",
      description: "Quiet aid versus public facing service.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },

    // Service and Charity indicators
    {
      id: "volunteerCapacity",
      type: "indicator",
      name: "Volunteer Capacity",
      description: "Availability of unpaid labor.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
    },
    {
      id: "aidEfficiency",
      type: "indicator",
      name: "Aid Efficiency",
      description: "Effectiveness of converting resources into impact.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
    },
    {
      id: "socialTrust",
      type: "indicator",
      name: "Social Trust",
      description: "Public confidence gained via charitable work.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
    },
    {
      id: "serviceReach",
      type: "indicator",
      name: "Service Reach",
      description: "Scale and scope of aid and services delivered.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
    },
    {
      id: "dependencyLoad",
      type: "indicator",
      name: "Dependency Load",
      description: "Number of people reliant on the organization.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
    },
    {
      id: "memberCareCapacity",
      type: "indicator",
      name: "Member Care Capacity",
      description: "Ability to support members with care services.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
    },
    {
      id: "formationInfrastructure",
      type: "indicator",
      name: "Formation Infrastructure",
      description:
        "Institutions for training, education, and leadership development.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Service and Charity",
    },

    // Mission and Expansion stances
    {
      id: "growthPriority",
      type: "stance",
      name: "Growth Priority",
      description: "Preserve core versus expand aggressively.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "conversionThreshold",
      type: "stance",
      name: "Conversion Threshold",
      description: "Easy entry versus high commitment.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
      stanceCost: stanceCostSoft,
      stance: discreteLowMidHigh,
    },
    {
      id: "culturalAdaptation",
      type: "stance",
      name: "Cultural Adaptation",
      description: "Fixed identity versus contextualized expression.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "missionAutonomy",
      type: "stance",
      name: "Mission Autonomy",
      description: "Central control versus local mission freedom.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },
    {
      id: "ethicalEmphasis",
      type: "stance",
      name: "Ethical Emphasis",
      description: "Belief focused versus practice focused.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
      stanceCost: stanceCostSoft,
      stance: continuous01,
    },

    // Mission and Expansion indicators
    {
      id: "membershipSize",
      type: "indicator",
      name: "Membership Size",
      description: "Total affiliated members.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
    },
    {
      id: "attendanceRate",
      type: "indicator",
      name: "Attendance Rate",
      description: "Regular service attendance.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
    },
    {
      id: "culturalInfluence",
      type: "indicator",
      name: "Cultural Influence",
      description: "Societal and soft power impact.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
    },
    {
      id: "memberEthicalPractice",
      type: "indicator",
      name: "Member Ethical Practice",
      description: "Alignment of behavior with belief.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
    },
    {
      id: "evangelicalEffectiveness",
      type: "indicator",
      name: "Evangelical Effectiveness",
      description: "Ability to attract new members.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Mission and Expansion",
    },

    // Situations
    {
      id: "schismCrisis",
      type: "situation",
      name: "Schism Crisis",
      description:
        "Factions harden and breakaway pressure rises. Authority becomes harder to wield.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Situations",
      situation: { start: 0.65, stop: 0.45 },
      positive: false,
      startActive: false,
    },
    {
      id: "reformMomentum",
      type: "situation",
      name: "Reform Momentum",
      description:
        "Widespread appetite for change and renewal. Teaching and formation improve quickly.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Situations",
      situation: { start: 0.6, stop: 0.4 },
      positive: true,
    },
    {
      id: "financialScandal",
      type: "situation",
      name: "Financial Scandal",
      description:
        "A scandal hits. Trust collapses and corruption scrutiny rises until reforms stabilize finances.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Situations",
      situation: { start: 0.6, stop: 0.4 },
      positive: false,
    },
    {
      id: "revivalWave",
      type: "situation",
      name: "Revival Wave",
      description:
        "A wave of enthusiasm boosts participation and growth, but can increase volatility.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Situations",
      situation: { start: 0.62, stop: 0.42 },
      positive: true,
    },
    {
      id: "leadershipCrisis",
      type: "situation",
      name: "Leadership Crisis",
      description:
        "Leadership is distrusted and overstretched. Capacity and implementation suffer.",
      domain: { min: 0, max: 1, clamp: true },
      category: "Situations",
      situation: { start: 0.6, stop: 0.49 },
      positive: false,
    },
  ],

  effects: [
    // Baselines
    { sourceId: "_default_", targetId: "budget", magnitude: 0.12 },
    { sourceId: "_default_", targetId: "authority", magnitude: 0.1 },

    // Governance stances to governance indicators
    {
      sourceId: "authorityCentralization",
      targetId: "governanceReach",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "authorityCentralization",
      targetId: "congregationalCohesion",
      magnitude: 0.015,
      inertiaTurns: 2,
    },
    {
      sourceId: "authorityCentralization",
      targetId: "leadershipTrust",
      magnitude: -0.01,
      inertiaTurns: 2,
    },
    {
      sourceId: "decisionFormalization",
      targetId: "governanceEffectiveness",
      magnitude: 0.025,
      inertiaTurns: 2,
    },
    {
      sourceId: "decisionFormalization",
      targetId: "leadershipTrust",
      magnitude: 0.01,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipAccountability",
      targetId: "leadershipTrust",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipAccountability",
      targetId: "governanceEffectiveness",
      magnitude: 0.015,
      inertiaTurns: 2,
    },
    {
      sourceId: "disciplinaryStrictness",
      targetId: "congregationalCohesion",
      magnitude: 0.015,
      inertiaTurns: 2,
    },
    {
      sourceId: "disciplinaryStrictness",
      targetId: "memberLoyalty",
      magnitude: -0.015,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipDevelopmentInvestment",
      targetId: "leadershipCapacity",
      magnitude: 0.03,
      inertiaTurns: 3,
    },
    {
      sourceId: "leadershipDevelopmentInvestment",
      targetId: "governanceReach",
      magnitude: 0.015,
      inertiaTurns: 3,
    },

    // Governance indicators internal couplings
    {
      sourceId: "leadershipCapacity",
      targetId: "governanceEffectiveness",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipTrust",
      targetId: "memberLoyalty",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "governanceEffectiveness",
      targetId: "congregationalCohesion",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "congregationalCohesion",
      targetId: "governanceReach",
      magnitude: 0.01,
      inertiaTurns: 2,
    },

    // Belief and Teaching stances to indicators
    {
      sourceId: "doctrinalBoundaryWidth",
      targetId: "confessionalRigidity",
      magnitude: -0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "doctrinalBoundaryWidth",
      targetId: "doctrinalClarity",
      magnitude: 0.015,
      inertiaTurns: 2,
    },
    {
      sourceId: "teachingCentralization",
      targetId: "doctrinalClarity",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "teachingCentralization",
      targetId: "layTheologicalLiteracy",
      magnitude: 0.015,
      inertiaTurns: 3,
    },
    {
      sourceId: "teachingAccessibilityPriority",
      targetId: "teachingAccessibility",
      magnitude: 0.035,
      inertiaTurns: 2,
    },
    {
      sourceId: "teachingAccessibilityPriority",
      targetId: "theologicalComplexity",
      magnitude: -0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "theologicalDepthEmphasis",
      targetId: "theologicalComplexity",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "theologicalDepthEmphasis",
      targetId: "clergyQuality",
      magnitude: 0.02,
      inertiaTurns: 3,
    },
    {
      sourceId: "catechesisIntensity",
      targetId: "layTheologicalLiteracy",
      magnitude: 0.03,
      inertiaTurns: 3,
    },
    {
      sourceId: "catechesisIntensity",
      targetId: "faithAdherence",
      magnitude: 0.025,
      inertiaTurns: 3,
    },

    // Belief and Teaching indicator couplings
    {
      sourceId: "clergyQuality",
      targetId: "layTheologicalLiteracy",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "doctrinalClarity",
      targetId: "faithAdherence",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "teachingAccessibility",
      targetId: "faithAdherence",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "theologicalComplexity",
      targetId: "teachingAccessibility",
      magnitude: -0.02,
      inertiaTurns: 2,
    },

    // Ritual stances to ritual indicators
    {
      sourceId: "ritualIntensity",
      targetId: "memberBurden",
      magnitude: 0.03,
      inertiaTurns: 1,
    },
    {
      sourceId: "ritualIntensity",
      targetId: "activeParticipation",
      magnitude: -0.015,
      inertiaTurns: 2,
    },
    {
      sourceId: "ritualStandardization",
      targetId: "ritualCohesion",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "ritualStandardization",
      targetId: "ritualQuality",
      magnitude: 0.015,
      inertiaTurns: 2,
    },
    {
      sourceId: "clergyExclusivityInRituals",
      targetId: "leadershipBurden",
      magnitude: 0.03,
      inertiaTurns: 1,
    },
    {
      sourceId: "clergyExclusivityInRituals",
      targetId: "ritualQuality",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "emotionalExpressionNorms",
      targetId: "worshipEngagement",
      magnitude: 0.02,
      inertiaTurns: 1,
    },
    {
      sourceId: "emotionalExpressionNorms",
      targetId: "emotionalVolatility",
      magnitude: 0.02,
      inertiaTurns: 1,
    },
    {
      sourceId: "participationExpectation",
      targetId: "activeParticipation",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "participationExpectation",
      targetId: "memberBurden",
      magnitude: 0.015,
      inertiaTurns: 1,
    },

    // Ritual indicator couplings
    {
      sourceId: "memberBurden",
      targetId: "activeParticipation",
      magnitude: -0.03,
      inertiaTurns: 1,
    },
    {
      sourceId: "leadershipBurden",
      targetId: "ritualQuality",
      magnitude: -0.02,
      inertiaTurns: 1,
    },
    {
      sourceId: "ritualCohesion",
      targetId: "worshipEngagement",
      magnitude: 0.01,
      inertiaTurns: 2,
    },
    {
      sourceId: "emotionalVolatility",
      targetId: "worshipEngagement",
      magnitude: -0.01,
      inertiaTurns: 1,
    },

    // Finance stances to finance indicators
    {
      sourceId: "fundingModel",
      targetId: "offering",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "fundingModel",
      targetId: "financialBurden",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "financialCentralization",
      targetId: "financialStability",
      magnitude: 0.015,
      inertiaTurns: 3,
    },
    {
      sourceId: "financialCentralization",
      targetId: "corruptionRisk",
      magnitude: 0.015,
      inertiaTurns: 3,
    },
    {
      sourceId: "transparencyLevel",
      targetId: "financialTransparencyIndex",
      magnitude: 0.04,
      inertiaTurns: 1,
    },
    {
      sourceId: "transparencyLevel",
      targetId: "corruptionRisk",
      magnitude: -0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "spendingPriority",
      targetId: "expenditure",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "reservePolicy",
      targetId: "debtAndReserves",
      magnitude: 0.03,
      inertiaTurns: 3,
    },
    {
      sourceId: "reservePolicy",
      targetId: "expenditure",
      magnitude: -0.015,
      inertiaTurns: 2,
    },

    // Finance indicator couplings
    {
      sourceId: "currentEconomy",
      targetId: "income",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "offering",
      targetId: "income",
      magnitude: 0.03,
      inertiaTurns: 1,
    },
    {
      sourceId: "donations",
      targetId: "income",
      magnitude: 0.02,
      inertiaTurns: 1,
    },
    {
      sourceId: "income",
      targetId: "financialStability",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "expenditure",
      targetId: "financialStability",
      magnitude: -0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "debtAndReserves",
      targetId: "financialStability",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "financialTransparencyIndex",
      targetId: "financialTrust",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "corruptionRisk",
      targetId: "financialTrust",
      magnitude: -0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "financialBurden",
      targetId: "offering",
      magnitude: -0.02,
      inertiaTurns: 2,
    },

    // Service stances to service indicators
    {
      sourceId: "serviceOrientation",
      targetId: "serviceReach",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "serviceOrientation",
      targetId: "memberCareCapacity",
      magnitude: -0.015,
      inertiaTurns: 2,
    },
    {
      sourceId: "serviceScaleStrategy",
      targetId: "aidEfficiency",
      magnitude: 0.02,
      inertiaTurns: 3,
    },
    {
      sourceId: "serviceScaleStrategy",
      targetId: "serviceReach",
      magnitude: 0.015,
      inertiaTurns: 3,
    },
    {
      sourceId: "serviceProfessionalization",
      targetId: "aidEfficiency",
      magnitude: 0.02,
      inertiaTurns: 3,
    },
    {
      sourceId: "serviceProfessionalization",
      targetId: "volunteerCapacity",
      magnitude: -0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "aidConditionality",
      targetId: "dependencyLoad",
      magnitude: -0.02,
      inertiaTurns: 3,
    },
    {
      sourceId: "aidConditionality",
      targetId: "socialTrust",
      magnitude: -0.01,
      inertiaTurns: 2,
    },
    {
      sourceId: "serviceVisibility",
      targetId: "socialTrust",
      magnitude: 0.02,
      inertiaTurns: 2,
    },

    // Service indicator couplings
    {
      sourceId: "volunteerCapacity",
      targetId: "serviceReach",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "aidEfficiency",
      targetId: "serviceReach",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "serviceReach",
      targetId: "socialTrust",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "dependencyLoad",
      targetId: "memberCareCapacity",
      magnitude: -0.01,
      inertiaTurns: 2,
    },

    // Mission stances to mission indicators
    {
      sourceId: "growthPriority",
      targetId: "evangelicalEffectiveness",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "growthPriority",
      targetId: "membershipSize",
      magnitude: 0.02,
      inertiaTurns: 3,
    },
    {
      sourceId: "conversionThreshold",
      targetId: "evangelicalEffectiveness",
      magnitude: -0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "conversionThreshold",
      targetId: "faithAdherence",
      magnitude: 0.015,
      inertiaTurns: 3,
    },
    {
      sourceId: "culturalAdaptation",
      targetId: "culturalInfluence",
      magnitude: 0.02,
      inertiaTurns: 3,
    },
    {
      sourceId: "missionAutonomy",
      targetId: "membershipSize",
      magnitude: 0.01,
      inertiaTurns: 3,
    },
    {
      sourceId: "ethicalEmphasis",
      targetId: "memberEthicalPractice",
      magnitude: 0.03,
      inertiaTurns: 3,
    },

    // Mission indicator couplings
    {
      sourceId: "membershipSize",
      targetId: "culturalInfluence",
      magnitude: 0.02,
      inertiaTurns: 3,
    },
    {
      sourceId: "attendanceRate",
      targetId: "memberLoyalty",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "faithAdherence",
      targetId: "memberEthicalPractice",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "memberEthicalPractice",
      targetId: "culturalInfluence",
      magnitude: 0.015,
      inertiaTurns: 2,
    },

    // Cross category couplings
    {
      sourceId: "doctrinalClarity",
      targetId: "congregationalCohesion",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "faithAdherence",
      targetId: "memberLoyalty",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "clergyQuality",
      targetId: "leadershipTrust",
      magnitude: 0.02,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipCapacity",
      targetId: "clergyQuality",
      magnitude: 0.01,
      inertiaTurns: 3,
    },
    {
      sourceId: "socialTrust",
      targetId: "leadershipTrust",
      magnitude: 0.01,
      inertiaTurns: 2,
    },
    {
      sourceId: "financialTrust",
      targetId: "memberLoyalty",
      magnitude: 0.01,
      inertiaTurns: 2,
    },
    {
      sourceId: "financialStability",
      targetId: "governanceEffectiveness",
      magnitude: 0.01,
      inertiaTurns: 2,
    },

    // Budget dynamics
    {
      sourceId: "income",
      targetId: "budget",
      magnitude: 0.18,
      inertiaTurns: 1,
    },
    {
      sourceId: "expenditure",
      targetId: "budget",
      magnitude: -0.2,
      inertiaTurns: 1,
    },
    {
      sourceId: "serviceReach",
      targetId: "budget",
      magnitude: -0.08,
      inertiaTurns: 1,
    },
    {
      sourceId: "evangelicalEffectiveness",
      targetId: "budget",
      magnitude: -0.05,
      inertiaTurns: 1,
    },

    // Authority dynamics
    {
      sourceId: "leadershipTrust",
      targetId: "authority",
      magnitude: 0.25,
      inertiaTurns: 1,
    },
    {
      sourceId: "governanceEffectiveness",
      targetId: "authority",
      magnitude: 0.2,
      inertiaTurns: 1,
    },
    {
      sourceId: "congregationalCohesion",
      targetId: "authority",
      magnitude: 0.15,
      inertiaTurns: 2,
    },
    {
      sourceId: "corruptionRisk",
      targetId: "authority",
      magnitude: -0.25,
      inertiaTurns: 1,
    },
    {
      sourceId: "financialStability",
      targetId: "authority",
      magnitude: 0.1,
      inertiaTurns: 2,
    },


    // --- Situation: Schism Crisis ---
    // Higher when cohesion and loyalty are low, plus higher when rigidity is high.
    // You can tune these magnitudes a lot. These values are intentionally moderate.
    {
      sourceId: "_default_",
      targetId: "schismCrisis",
      magnitude: 0.1,
      inertiaTurns: 2,
    },
    {
      sourceId: "congregationalCohesion",
      targetId: "schismCrisis",
      magnitude: -0.45,
      inertiaTurns: 3,
    },
    {
      sourceId: "memberLoyalty",
      targetId: "schismCrisis",
      magnitude: -0.35,
      inertiaTurns: 3,
    },
    {
      sourceId: "confessionalRigidity",
      targetId: "schismCrisis",
      magnitude: 0.25,
      inertiaTurns: 3,
    },
    {
      sourceId: "leadershipTrust",
      targetId: "schismCrisis",
      magnitude: -0.15,
      inertiaTurns: 2,
    },

    // Outgoing when active
    {
      sourceId: "schismCrisis",
      targetId: "memberLoyalty",
      magnitude: -0.04,
      inertiaTurns: 2,
    },
    {
      sourceId: "schismCrisis",
      targetId: "congregationalCohesion",
      magnitude: -0.05,
      inertiaTurns: 2,
    },
    {
      sourceId: "schismCrisis",
      targetId: "authority",
      magnitude: -0.06,
      inertiaTurns: 1,
    },

    // --- Situation: Reform Momentum ---
    // Higher when accessibility and literacy are high, plus when cohesion is not collapsing.
    {
      sourceId: "_default_",
      targetId: "reformMomentum",
      magnitude: 0.1,
      inertiaTurns: 2,
    },
    {
      sourceId: "teachingAccessibility",
      targetId: "reformMomentum",
      magnitude: 0.35,
      inertiaTurns: 3,
    },
    {
      sourceId: "layTheologicalLiteracy",
      targetId: "reformMomentum",
      magnitude: 0.25,
      inertiaTurns: 3,
    },
    {
      sourceId: "congregationalCohesion",
      targetId: "reformMomentum",
      magnitude: 0.15,
      inertiaTurns: 2,
    },
    {
      sourceId: "confessionalRigidity",
      targetId: "reformMomentum",
      magnitude: -0.2,
      inertiaTurns: 3,
    },

    // Outgoing when active
    {
      sourceId: "reformMomentum",
      targetId: "doctrinalClarity",
      magnitude: 0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "reformMomentum",
      targetId: "clergyQuality",
      magnitude: 0.02,
      inertiaTurns: 3,
    },
    {
      sourceId: "reformMomentum",
      targetId: "leadershipCapacity",
      magnitude: 0.02,
      inertiaTurns: 3,
    },

    // --- Situation: Financial Scandal ---
    // Higher when corruption risk is high and transparency is low, with trust feeding it too.
    {
      sourceId: "_default_",
      targetId: "financialScandal",
      magnitude: 0.1,
      inertiaTurns: 2,
    },
    {
      sourceId: "corruptionRisk",
      targetId: "financialScandal",
      magnitude: 0.5,
      inertiaTurns: 2,
    },
    {
      sourceId: "financialTransparencyIndex",
      targetId: "financialScandal",
      magnitude: -0.35,
      inertiaTurns: 2,
    },
    {
      sourceId: "financialTrust",
      targetId: "financialScandal",
      magnitude: -0.2,
      inertiaTurns: 2,
    },

    // Outgoing when active
    {
      sourceId: "financialScandal",
      targetId: "financialTrust",
      magnitude: -0.06,
      inertiaTurns: 1,
    },
    {
      sourceId: "financialScandal",
      targetId: "memberLoyalty",
      magnitude: -0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "financialScandal",
      targetId: "authority",
      magnitude: -0.05,
      inertiaTurns: 1,
    },

    // --- Situation: Revival Wave ---
    // Higher when worship engagement and participation are high. Volatility also boosts it.
    {
      sourceId: "_default_",
      targetId: "revivalWave",
      magnitude: 0.08,
      inertiaTurns: 2,
    },
    {
      sourceId: "worshipEngagement",
      targetId: "revivalWave",
      magnitude: 0.35,
      inertiaTurns: 2,
    },
    {
      sourceId: "activeParticipation",
      targetId: "revivalWave",
      magnitude: 0.25,
      inertiaTurns: 2,
    },
    {
      sourceId: "emotionalVolatility",
      targetId: "revivalWave",
      magnitude: 0.2,
      inertiaTurns: 1,
    },

    // Outgoing when active
    {
      sourceId: "revivalWave",
      targetId: "attendanceRate",
      magnitude: 0.04,
      inertiaTurns: 2,
    },
    {
      sourceId: "revivalWave",
      targetId: "membershipSize",
      magnitude: 0.03,
      inertiaTurns: 3,
    },
    {
      sourceId: "revivalWave",
      targetId: "emotionalVolatility",
      magnitude: 0.03,
      inertiaTurns: 1,
    },

    // --- Situation: Leadership Crisis ---
    // Higher when trust and capacity are low and burden is high.
    {
      sourceId: "_default_",
      targetId: "leadershipCrisis",
      magnitude: 0.1,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipTrust",
      targetId: "leadershipCrisis",
      magnitude: -0.35,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipCapacity",
      targetId: "leadershipCrisis",
      magnitude: -0.3,
      inertiaTurns: 3,
    },
    {
      sourceId: "leadershipBurden",
      targetId: "leadershipCrisis",
      magnitude: 0.35,
      inertiaTurns: 2,
    },

    // Outgoing when active
    {
      sourceId: "leadershipCrisis",
      targetId: "governanceEffectiveness",
      magnitude: -0.04,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipCrisis",
      targetId: "leadershipCapacity",
      magnitude: -0.03,
      inertiaTurns: 2,
    },
    {
      sourceId: "leadershipCrisis",
      targetId: "authority",
      magnitude: -0.04,
      inertiaTurns: 1,
    },
  ],
};
