import { PilotPackV2 } from "../lib/graphTypes";

export const pilotPackV2: PilotPackV2 = {
  version: "pilot_v2",
  title: "Pilot Scenario",
  turnTarget: 30,

  authorityId: "authority",
  authorityIncomeId: "authorityIncome",
  authorityMin: 0,
  authorityMax: 20,

  nodes: [
    // Stances
    {
      id: "confessionalStrictness",
      type: "stance",
      name: "Confessional Strictness",
      description: "How strict subscription and boundaries are.",
      startValue: 0.5,
      clampMin: 0,
      clampMax: 1,
    },
    {
      id: "seminaryInvestment",
      type: "stance",
      name: "Seminary Investment",
      description: "Investment in training and education.",
      startValue: 0.4,
      clampMin: 0,
      clampMax: 1,
    },
    {
      id: "disciplineEnforcement",
      type: "stance",
      name: "Discipline Enforcement",
      description: "How strongly discipline is applied.",
      startValue: 0.45,
      clampMin: 0,
      clampMax: 1,
    },
    {
      id: "ecumenismOpenness",
      type: "stance",
      name: "Ecumenism Openness",
      description: "Willingness to cooperate across lines.",
      startValue: 0.35,
      clampMin: 0,
      clampMax: 1,
    },

    // Indicators
    {
      id: "clergyQuality",
      type: "indicator",
      name: "Clergy Quality",
      description: "Training and competence.",
      startValue: 0.45,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.05,
    },
    {
      id: "doctrinalClarity",
      type: "indicator",
      name: "Doctrinal Clarity",
      description: "How coherent teaching and confession are.",
      startValue: 0.5,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.05,
    },
    {
      id: "unityCohesion",
      type: "indicator",
      name: "Unity Cohesion",
      description: "Internal cohesion across factions.",
      startValue: 0.55,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.05,
    },
    {
      id: "schismPressure",
      type: "indicator",
      name: "Schism Pressure",
      description: "Risk of fragmentation.",
      startValue: 0.35,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.05,
    },
    {
      id: "publicLegitimacy",
      type: "indicator",
      name: "Public Legitimacy",
      description: "Standing with wider society.",
      startValue: 0.5,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.05,
    },
    {
      id: "institutionalIntegrity",
      type: "indicator",
      name: "Institutional Integrity",
      description: "Trust and lack of corruption.",
      startValue: 0.6,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.05,
    },
    {
      id: "spiritualVitality",
      type: "indicator",
      name: "Spiritual Vitality",
      description: "Energy of worship and devotion.",
      startValue: 0.5,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.05,
    },

    // Factions
    {
      id: "confessionalists",
      type: "faction",
      name: "Confessionalists",
      description: "Prefer clarity and strict boundaries.",
      startValue: 0.5,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.08,
    },
    {
      id: "revivalists",
      type: "faction",
      name: "Revivalists",
      description: "Prefer vitality over control.",
      startValue: 0.5,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.08,
    },
    {
      id: "institutionalists",
      type: "faction",
      name: "Institutionalists",
      description: "Prefer integrity and legitimacy.",
      startValue: 0.5,
      clampMin: 0,
      clampMax: 1,
      maxDeltaPerTick: 0.08,
    },

    // Resources
    {
      id: "authorityIncome",
      type: "resource",
      name: "Authority Income",
      description: "Authority gained per turn.",
      startValue: 0,
      clampMin: 0,
      clampMax: 10,
      maxDeltaPerTick: 10,
    },
    {
      id: "authority",
      type: "resource",
      name: "Authority",
      description: "Authority capital available to spend.",
      startValue: 10,
      clampMin: 0,
      clampMax: 20,
      maxDeltaPerTick: 10,
    },
  ],

  stanceCosts: {
    confessionalStrictness: { baseCost: 1, costPerPoint: 6, maxDeltaPerTurn: 0.2 },
    seminaryInvestment: { baseCost: 1, costPerPoint: 7, maxDeltaPerTurn: 0.2 },
    disciplineEnforcement: { baseCost: 1, costPerPoint: 5, maxDeltaPerTurn: 0.25 },
    ecumenismOpenness: { baseCost: 1, costPerPoint: 5, maxDeltaPerTurn: 0.25 },
  },

  edges: [
    // Stance -> indicator
    {
      id: "e_confStrict_to_clarity",
      sourceId: "confessionalStrictness",
      targetId: "doctrinalClarity",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.10 },
      inertiaTurns: 3,
      maxAbsContribution: 0.03,
    },
    {
      id: "e_confStrict_to_schism",
      sourceId: "confessionalStrictness",
      targetId: "schismPressure",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.10 },
      inertiaTurns: 2,
      maxAbsContribution: 0.03,
    },
    {
      id: "e_seminary_to_clergyQ",
      sourceId: "seminaryInvestment",
      targetId: "clergyQuality",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.12 },
      inertiaTurns: 4,
      maxAbsContribution: 0.03,
    },
    {
      id: "e_discipline_to_integrity",
      sourceId: "disciplineEnforcement",
      targetId: "institutionalIntegrity",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.08 },
      inertiaTurns: 2,
      maxAbsContribution: 0.03,
    },
    {
      id: "e_ecumenism_to_legitimacy",
      sourceId: "ecumenismOpenness",
      targetId: "publicLegitimacy",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.08 },
      inertiaTurns: 2,
      maxAbsContribution: 0.03,
    },

    // Indicator -> indicator
    {
      id: "e_clergyQ_to_clarity",
      sourceId: "clergyQuality",
      targetId: "doctrinalClarity",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.06 },
      inertiaTurns: 3,
      maxAbsContribution: 0.02,
    },
    {
      id: "e_clarity_to_unity",
      sourceId: "doctrinalClarity",
      targetId: "unityCohesion",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.05 },
      inertiaTurns: 3,
      maxAbsContribution: 0.02,
    },
    {
      id: "e_clarity_to_schism",
      sourceId: "doctrinalClarity",
      targetId: "schismPressure",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.04 },
      inertiaTurns: 3,
      maxAbsContribution: 0.02,
    },
    {
      id: "e_integrity_to_legitimacy",
      sourceId: "institutionalIntegrity",
      targetId: "publicLegitimacy",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.05 },
      inertiaTurns: 3,
      maxAbsContribution: 0.02,
    },

    // Indicator -> faction
    {
      id: "e_clarity_to_confessionalists",
      sourceId: "doctrinalClarity",
      targetId: "confessionalists",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.10 },
      inertiaTurns: 2,
      maxAbsContribution: 0.04,
    },
    {
      id: "e_vitality_to_revivalists",
      sourceId: "spiritualVitality",
      targetId: "revivalists",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.10 },
      inertiaTurns: 2,
      maxAbsContribution: 0.04,
    },
    {
      id: "e_integrity_to_institutionalists",
      sourceId: "institutionalIntegrity",
      targetId: "institutionalists",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.10 },
      inertiaTurns: 2,
      maxAbsContribution: 0.04,
    },

    // Stance -> faction (direct reactions)
    {
      id: "e_ecumenism_to_confessionalists",
      sourceId: "ecumenismOpenness",
      targetId: "confessionalists",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: -0.06 },
      inertiaTurns: 2,
      maxAbsContribution: 0.03,
    },
    {
      id: "e_discipline_to_revivalists",
      sourceId: "disciplineEnforcement",
      targetId: "revivalists",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: -0.05 },
      inertiaTurns: 2,
      maxAbsContribution: 0.03,
    },

    // Faction -> indicator (pressure back into system)
    {
      id: "e_confessionalists_to_unity",
      sourceId: "confessionalists",
      targetId: "unityCohesion",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.04 },
      inertiaTurns: 2,
      maxAbsContribution: 0.02,
    },
    {
      id: "e_revivalists_to_vitality",
      sourceId: "revivalists",
      targetId: "spiritualVitality",
      sourceTransform: { kind: "centered", center: 0.5 },
      rule: { kind: "linear", strength: 0.04 },
      inertiaTurns: 2,
      maxAbsContribution: 0.02,
    },

    // Indicators and factions -> authorityIncome
    {
      id: "e_legitimacy_to_income",
      sourceId: "publicLegitimacy",
      targetId: "authorityIncome",
      sourceTransform: { kind: "raw" },
      rule: { kind: "linear", strength: 4.0, bias: 0 },
      inertiaTurns: 1,
    },
    {
      id: "e_unity_to_income",
      sourceId: "unityCohesion",
      targetId: "authorityIncome",
      sourceTransform: { kind: "raw" },
      rule: { kind: "linear", strength: 3.0, bias: 0 },
      inertiaTurns: 1,
    },
    {
      id: "e_schism_to_income",
      sourceId: "schismPressure",
      targetId: "authorityIncome",
      sourceTransform: { kind: "raw" },
      rule: { kind: "linear", strength: -5.0, bias: 0 },
      inertiaTurns: 1,
    },
    {
      id: "e_integrity_to_income",
      sourceId: "institutionalIntegrity",
      targetId: "authorityIncome",
      sourceTransform: { kind: "raw" },
      rule: { kind: "linear", strength: 2.0, bias: 0 },
      inertiaTurns: 1,
    },
    {
      id: "e_institutionalists_to_income",
      sourceId: "institutionalists",
      targetId: "authorityIncome",
      sourceTransform: { kind: "raw" },
      rule: { kind: "linear", strength: 1.5, bias: 0 },
      inertiaTurns: 1,
    },

    // Base income via bias using a dummy self edge on authorityIncome
    {
      id: "e_income_base",
      sourceId: "authorityIncome",
      targetId: "authorityIncome",
      sourceTransform: { kind: "raw" },
      rule: { kind: "linear", strength: 0.0, bias: 6.0 },
      inertiaTurns: 1,
    },
  ],

  initialValues: {
    // You can override any startValue here if desired
  },
};
